ochki:
  permalink: solntsiezashchitnyie-ochki
  name: Солнцезащитные очки в салонах «Оптик Сити». Bvlgari, Cartier, Dior, Kenzo, Swarovski и другие бренды.
  count_on_hand: 500
  tax_category_id: 
  discount: 50
  created_at: <%= Time.zone.now.to_s(:db) %>
  available_on: <%= Time.zone.now.to_s(:db) %>
  shipping_category_id: 
  available_till: <%= (Time.zone.now+10.days).to_s(:db) %>
  updated_at: <%= Time.zone.now.to_s(:db) %>
  featured: false
  deleted_at: 
  meta_keywords: 
  meta_description: 
  action_type: 0
  description: "Лучший способ подготовки кожи любого типа к пляжному сезону – солярий. Сеть студий «Ультра Сан» дарит безлиминый абонемент на посещение 1 или 3 месяца загара в вертикальном или горизонтальном турбосолярии.\r\n\r\n\r\n\r\nГоризонтальный солярий – выбор тех, кто хочет расслабиться после тяжелого рабочего дня, а вертикальный подойдет тем, кто хочет получить максимально ровный загар. Свет ламп вертикального солярия равномерно ложится на всю поверхность тела, затрагивая даже труднодоступные участки: внутренние поверхности рук и бедер. Просторная кабина не ограничивает свободу движения, а направленное по спирали кондиционирование предотвращает перегрев.\r\n\r\n\r\n\r\nКосметика для загара помогает добиться самых разных эффектов: например, при помощи крема, разогревающего отдельные точки кожи, можно покрыться почти что настоящими веснушками. «Ультра Сан» - это сеть студий загара, расположенных в четырех районах Москвы. 6 видов вертикальных турбосоляриев, горизонтальные солярии и большой выбор косметики для загара. В студиях представлены солярии, оснащенные аудиосистемами и системами водного орошения.\r\n\r\nУл. Строителей, д. 7, корп. 1 (м. «Университет»),\r\nтел.: +7 495 930-61-35\r\nУл. Новослободская, д. 62, корп. 19 (м. «Савеловская»),\r\nтел.: +7 495 609-24-06\r\nУл. Вешняковская, д. 24, корп. 1 (м. «Выхино»),\r\nтел.: +7 495 786-31-02\r\nУл. Знаменские Садки, д. 3, корп. 1 (м. «Бульвар Д. Донского»),\r\nтел.: +7 495 712-17-72\r\nwww.ultra-sun.ru\r\nПосмотреть прайс\r\nЧасы работы: пн. — вс. 10:00 — 21:00"
  state_id: 1









