Допустим /^в сервисе есть geo$/ do
  YAML::load_file("db/default/countries.yml").each {|key, value|
    country = Country.create(:name => value["name"], :iso_name => value["iso_name"], :iso => value["iso"], :iso3 => value["iso"], :numcode => value["numcode"])
  }

  russia = Country.find_by_iso("RU")
  State.create(:name => "Москва", :country_id => russia.id)
  State.create(:name => "Екатеринбург", :country_id => russia.id)
  State.create(:name => "Красноярск", :country_id => russia.id)
  State.create(:name => "Оренбург", :country_id => russia.id)
  State.create(:name => "Тюмень", :country_id => russia.id)
  State.create(:name => "Санкт-Петербург", :country_id => russia.id)
  State.create(:name => "Иркутск", :country_id => russia.id)
  State.create(:name => "Нижний Новгород", :country_id => russia.id)
  State.create(:name => "Пермь", :country_id => russia.id)
  State.create(:name => "Ульяновск", :country_id => russia.id)
  State.create(:name => "Барнаул", :country_id => russia.id)
  State.create(:name => "Казань", :country_id => russia.id)
  State.create(:name => "Новокузнецк", :country_id => russia.id)
  State.create(:name => "Ростов-на-Дону", :country_id => russia.id)
  State.create(:name => "Уфа", :country_id => russia.id)
  State.create(:name => "Волгоград", :country_id => russia.id)
  State.create(:name => "Кемерово", :country_id => russia.id)
  State.create(:name => "Новосибирск", :country_id => russia.id)
  State.create(:name => "Самара", :country_id => russia.id)
  State.create(:name => "Челябинск", :country_id => russia.id)
  State.create(:name => "Воронеж", :country_id => russia.id)
  State.create(:name => "Краснодар", :country_id => russia.id)
  State.create(:name => "Омск", :country_id => russia.id)
  State.create(:name => "Саратов", :country_id => russia.id)
  State.create(:name => "Ярославль", :country_id => russia.id)

  ua = Country.find_by_iso("UA")
  State.create(:name => "Киев", :country_id => ua.id)
  State.create(:name => "Днепропетровск", :country_id => ua.id)
  State.create(:name => "Донецк", :country_id => ua.id)
  State.create(:name => "Львов", :country_id => ua.id)
  State.create(:name => "Одесса", :country_id => ua.id)
  State.create(:name => "Харьков", :country_id => ua.id)
end
